apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m5g5a55ow-java-springboot
  janus-idp.io/tekton: m5g5a55ow-java-springboot
  backstage.io/kubernetes-id: m5g5a55ow-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m5g5a55ow-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
